### ISSUE TITLE
cachix cache?

### ISSUE THREAD

**Issue by bbigras** [mlvzk/manix#18]
It could be nice. My nix config uses a lot of them and it speeds the compile time a lot. Especially when nixos-unstable moves forward and my compile time takes like 3 hours.

nix.dev has a nice template for that using github actions and niv. https://github.com/nix-dot-dev/getting-started-nix-template

Personally I also use [nix-build-uncached](https://github.com/Mic92/nix-build-uncached).

**Comment by mlvzk** [comment]
It should soon be in the unstable channel(was merged to master 2 days ago). Will you still need this?

**Comment by mlvzk** [comment]
It should soon be in the unstable channel(got merged to master 2 days ago). Will you still need it?

**Comment by bbigras** [comment]
I use unstable, so I won't need it.

Thank you very much.

**Comment by mlvzk** [comment]
@bbigras the nixos-unstable channel has been updated and now includes manix

**Comment by bbigras** [comment]
Thanks! I'm using it now with unstable.
